# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20180626_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='business',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
